// <auto-generated />
using System;
using J2.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace J2.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230519164652_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("J2.API.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("074d20a2-91b4-4920-a4e1-c3b0d6d6e0d8"),
                            CreatedOn = new DateTime(2023, 5, 19, 20, 16, 52, 272, DateTimeKind.Local).AddTicks(1270),
                            FirstName = "جورج",
                            LastName = "اورول"
                        },
                        new
                        {
                            Id = new Guid("f0189a83-960f-432b-b90e-faf807a7bf86"),
                            CreatedOn = new DateTime(2023, 5, 19, 20, 16, 52, 272, DateTimeKind.Local).AddTicks(1340),
                            FirstName = "جین",
                            LastName = "آستن"
                        });
                });

            modelBuilder.Entity("J2.API.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5e01212-2014-4d07-af07-d7fab460a404"),
                            AuthorId = new Guid("074d20a2-91b4-4920-a4e1-c3b0d6d6e0d8"),
                            DatePublished = new DateTime(1949, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "رمان",
                            Isbn = "12344",
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("J2.API.Models.Book", b =>
                {
                    b.HasOne("J2.API.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("J2.API.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
